try {
	${1}
} catch (Exception $e) {
    ${2:echo 'Caught exception: ',  $e->getMessage(), "\n"};
}

